version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - "6033:3306"
    volumes:
      - database_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    ports:
      - "8000:80"
    volumes:
      - ./wordpress:/var/www/html
      - ./themes/storefront-child:/var/www/html/wp-content/themes/storefront-child
      - ./backups:/var/www/html/wp-content/ai1wm-backups
    build: ./dockerfiles/wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

volumes:
  database_data:

